"""Genera el notebook 01-paysim-fraud-detection.ipynb con explicaciones didacticas."""
import json

cells = []

def md(source):
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [s if s.endswith("\n") else s + "\n" for s in source]
    })

def code(source):
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [s if s.endswith("\n") else s + "\n" for s in source]
    })

# =============================================================================
# CELDAS
# =============================================================================

md([
"# Deteccion de Fraude con PaySim + XGBoost\n",
"\n",
"> **Objetivo:** Entrenar un modelo supervisado de clasificacion binaria que detecte\n",
"> transacciones fraudulentas usando el dataset PaySim.\n",
">\n",
"> **Output:** Un archivo `.joblib` que nuestro sistema de produccion cargara para\n",
"> calcular `ml_score` en cada transaccion.\n",
"\n",
"---\n",
"\n",
"## Que vamos a hacer y por que?\n",
"\n",
"Nuestro sistema de deteccion de fraude tiene 3 capas:\n",
"\n",
"| Capa | Estado |\n",
"|------|--------|\n",
"| **Rule Engine** (6 reglas deterministas) | Ya funciona |\n",
"| **XGBoost** (ML supervisado) | Lo vamos a crear aqui |\n",
"| **Ensemble** (combina ambas) | Ya funciona |\n",
"\n",
"Hasta ahora `ml_score` estaba en 0 porque no teniamos modelo. Con PaySim vamos a\n",
"entrenar un **XGBoost clasificador** que aprenda a distinguir transacciones\n",
"fraudulentas de las normales.\n",
"\n",
"---\n",
"\n",
"## Que es PaySim?\n",
"\n",
"PaySim es un simulador de transacciones financieras mobile. Genera datos sinteticos\n",
"realistas basados en una muestra de transacciones reales de una empresa de finanzas\n",
"mobile de Africa.\n",
"\n",
"- **Tamano:** ~6 millones de transacciones\n",
"- **Fraudes:** ~0.1% (muy desbalanceado, como en la vida real)\n",
"- **Columnas:** interpretables (no PCA)\n",
"\n",
"| Columna | Significado |\n",
"|---------|-------------|\n",
"| `step` | Unidad de tiempo (1 step = 1 hora) |\n",
"| `type` | Tipo: PAYMENT, TRANSFER, CASH_OUT, DEBIT, CASH_IN |\n",
"| `amount` | Monto de la transaccion |\n",
"| `nameOrig` | ID del cliente que origina |\n",
"| `oldbalanceOrg` | Saldo del cliente ANTES de la transaccion |\n",
"| `newbalanceOrig` | Saldo del cliente DESPUES de la transaccion |\n",
"| `nameDest` | ID del destinatario |\n",
"| `oldbalanceDest` | Saldo del destinatario ANTES |\n",
"| `newbalanceDest` | Saldo del destinatario DESPUES |\n",
"| **`isFraud`** | **1 = fraude, 0 = legitimo (nuestro TARGET)** |\n",
"| `isFlaggedFraud` | 1 si el sistema ya lo marco (no lo usamos) |\n",
"\n",
"---\n",
"\n",
"## Arquitectura del modelo\n",
"\n",
"```\n",
"PaySim (raw) -> Feature Engineering -> SMOTE -> XGBoost -> .joblib\n",
"                                                       -> MLModelService.predict()\n",
"```\n",
"\n",
"---\n",
"\n",
"## Metricas que nos importan\n",
"\n",
"En deteccion de fraude, **no nos sirve el accuracy**. Si el 99.9% de las\n",
"transacciones son legitimas, un modelo que siempre diga \"legitimo\" tiene 99.9%\n",
"de accuracy pero no detecta NINGUN fraude.\n",
"\n",
"| Metrica | Por que importa |\n",
"|---------|-----------------|\n",
"| **Recall** | De todos los fraudes reales, cuantos detectamos? **Lo mas critico** |\n",
"| **Precision** | De los que marcamos como fraude, cuantos lo eran realmente? |\n",
"| **F1** | Balance entre precision y recall |\n",
"| **AUC-ROC** | Capacidad del modelo de separar clases |\n",
"| **Matriz de confusion** | Ver TP, FP, FN, TN |\n",
"\n",
"---\n",
])

code([
"# =============================================================================\n",
"# CELDA 1: IMPORTS Y CONFIGURACION\n",
"# =============================================================================\n",
"# Por que estos imports?:\n",
"#   - pandas: manipular el CSV como tabla\n",
"#   - numpy: operaciones matematicas rapidas\n",
"#   - train_test_split: separar datos en entrenamiento y prueba (fundamental\n",
"#     para evaluar si el modelo generaliza o solo memoriza)\n",
"#   - StandardScaler: estandarizar features (media=0, std=1). XGBoost no lo\n",
"#     necesita (los arboles no se ven afectados por la escala), pero lo\n",
"#     incluimos porque nuestro FeatureEngine de produccion podria necesitarlo\n",
"#   - SMOTE: tecnica de balanceo. Genera ejemplos sinteticos de la clase\n",
"#     minoritaria (fraude) para que el modelo no se sesgue\n",
"#   - XGBoost: nuestro clasificador. Gradient boosting con regularizacion.\n",
"#     Es el estado del arte para datos tabulares\n",
"#   - joblib: guardar/cargar el modelo entrenado en formato comprimido\n",
"#\n",
"# Dato curioso: XGBoost significa eXtreme Gradient Boosting. La \"X\" es\n",
"# por \"extreme\" porque optimiza el gradient boosting tradicional con\n",
"# regularizacion L1/L2, manejo de valores nulos, y paralelizacion.\n",
"\n",
"import pandas as pd\n",
"import numpy as np\n",
"from sklearn.model_selection import train_test_split\n",
"from sklearn.preprocessing import LabelEncoder\n",
"from sklearn.metrics import (\n",
"    classification_report,\n",
"    confusion_matrix,\n",
"    roc_auc_score,\n",
"    precision_recall_curve,\n",
"    f1_score,\n",
")\n",
"from imblearn.over_sampling import SMOTE\n",
"import xgboost as xgb\n",
"import joblib\n",
"import warnings\n",
"warnings.filterwarnings('ignore')\n",
"\n",
"print(\"Imports cargados correctamente\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 2: CARGA DEL DATASET\n",
"# =============================================================================\n",
"# PaySim tiene ~6.3M de filas y pesa ~300MB. Lo cargamos con pandas.\n",
"# dtype warning: pandas infiere tipos automaticamente. Con 6M filas\n",
"# conviene especificarlos para ahorrar memoria.\n",
"#\n",
"# Concepto: pd.read_csv() crea un DataFrame. Piensa en el como una\n",
"# hoja de calculo en memoria con operaciones vectorizadas (rapidas).\n",
"\n",
"PATH = r\"..\\transaccion\\PS_20174392719_1491204439457_log.csv\"\n",
"\n",
"df = pd.read_csv(PATH)\n",
"print(f\"Filas: {df.shape[0]:,}\")\n",
"print(f\"Columnas: {df.shape[1]}\")\n",
"print(f\"Memoria estimada: {df.memory_usage(deep=True).sum() / 1024**2:.1f} MB\")\n",
"df.head(3)\n",
])

code([
"# =============================================================================\n",
"# CELDA 3: ANALISIS EXPLORATORIO (EDA) - Distribuciones\n",
"# =============================================================================\n",
"# Antes de modelar hay que ENTENDER los datos. Esta es la parte mas\n",
"# importante de todo el pipeline de ML y la que mas se salta la gente.\n",
"#\n",
"# Preguntas que responder:\n",
"#   1. Cuantos fraudes hay? (balance de clases)\n",
"#   2. Que tipos de operacion existen?\n",
"#   3. En que tipo ocurren los fraudes?\n",
"#   4. Como se distribuyen los montos?\n",
"#\n",
"# La regla de oro: si no entiendes tus datos, no importa que modelo uses.\n",
"\n",
"print(\"=\" * 50)\n",
"print(\"DISTRIBUCION DE CLASES (isFraud)\")\n",
"print(\"=\" * 50)\n",
"fraud_counts = df[\"isFraud\"].value_counts()\n",
"fraud_pct = df[\"isFraud\"].value_counts(normalize=True) * 100\n",
"for label in [0, 1]:\n",
"    print(f\"  {label}: {fraud_counts[label]:>8,} transacciones ({fraud_pct[label]:.3f}%)\")\n",
"\n",
"print(f\"\\nProporcion: 1 fraude por cada {fraud_counts[0] // fraud_counts[1]:,} legitimas\")\n",
"\n",
"print(\"\\n\" + \"=\" * 50)\n",
"print(\"TIPOS DE OPERACION\")\n",
"print(\"=\" * 50)\n",
"print(df[\"type\"].value_counts().to_string())\n",
"\n",
"print(\"\\n\" + \"=\" * 50)\n",
"print(\"FRAUDES POR TIPO DE OPERACION\")\n",
"print(\"=\" * 50)\n",
"print(df[df[\"isFraud\"] == 1][\"type\"].value_counts().to_string())\n",
"\n",
"# Insight clave: los fraudes solo ocurren en TRANSFER y CASH_OUT.\n",
"# Por que? Porque son las unicas operaciones donde el dinero\n",
"# cambia de dueno. CASH_IN (deposito) no tiene sentido fraudarlo,\n",
"# PAYMENT y DEBIT son pagos a comercios registrados.\n",
])

code([
"# =============================================================================\n",
"# CELDA 4: VERIFICACION DE CONSISTENCIA\n",
"# =============================================================================\n",
"# PaySim tiene una propiedad interesante: cuando hay fraude en TRANSFER\n",
"# o CASH_OUT, el saldo de origen (oldbalanceOrg) se transfiere COMPLETO\n",
"# pero el saldo de destino (oldbalanceDest) suele ser 0.\n",
"#\n",
"# Esto es porque los fraudes en PaySim simulan cuentas tomadas:\n",
"# el atacante vacia la cuenta victima (oldbalanceOrg = amount)\n",
"# y la envia a una cuenta que no existia antes (oldbalanceDest = 0).\n",
"#\n",
"# Verificamos esta regla para entender los datos:\n",
"\n",
"fraudes = df[df[\"isFraud\"] == 1]\n",
"print(f\"Total fraudes: {len(fraudes)}\")\n",
"print(f\"  - TRANSFER: {len(fraudes[fraudes['type'] == 'TRANSFER'])}\")\n",
"print(f\"  - CASH_OUT: {len(fraudes[fraudes['type'] == 'CASH_OUT'])}\")\n",
"\n",
"# Regla del saldo: en fraudes TRANSFER, el saldo origen se vacia\n",
"org_balance_check = (\n",
"    fraudes[fraudes[\"type\"] == \"TRANSFER\"][\"oldbalanceOrg\"] == fraudes[fraudes[\"type\"] == \"TRANSFER\"][\"amount\"]\n",
").mean()\n",
"print(f\"\\nFraudes TRANSFER donde oldbalanceOrg == amount: {org_balance_check:.1%}\")\n",
"\n",
"# Regla del destino: en fraudes, el destino suele ser 0 (cuenta nueva)\n",
"dest_zero_check = (fraudes[\"oldbalanceDest\"] == 0).mean()\n",
"print(f\"Fraudes donde oldbalanceDest == 0 (cuenta nueva): {dest_zero_check:.1%}\")\n",
"\n",
"# Esto nos da una pista importante: el FeatureEngine podria incluir\n",
"# \"oldbalanceOrg == amount\" como feature. Es un patron de fraude clasico.\n",
])

code([
"# =============================================================================\n",
"# CELDA 5: FEATURE ENGINEERING - De PaySim a nuestro FeatureEngine\n",
"# =============================================================================\n",
"#\n",
"# Este es el corazon del notebook. Tenemos que transformar las columnas\n",
"# de PaySim a las 10 features que espera nuestro FeatureEngine.\n",
"#\n",
"# Nuestro FeatureEngine original espera:\n",
"#   [amount, amount_vs_user_avg, amount_vs_user_std, tx_count_5min,\n",
"#    tx_count_1h, hour_of_day, is_weekend, merchant_risk_level,\n",
"#    is_crypto, amount_round_number]\n",
"#\n",
"# PaySim no tiene user_id real, ni merchant_name, ni timestamp.\n",
"# Mapeamos lo que podemos y el resto lo dejamos en 0.\n",
"#\n",
"# MAPEO:\n",
"#   PaySim amount        -> amount (directo)\n",
"#   PaySim type          -> merchant_category (LabelEncoder)\n",
"#   amount / oldbalance  -> amount_vs_user_avg (aproximacion)\n",
"#   PaySim step % 24     -> hour_of_day\n",
"#   type=TRANSFER        -> is_crypto = 1 (es la analogia mas cercana)\n",
"#   type=CASH_OUT/TRANSFER -> merchant_risk_level = 1\n",
"#   amount % 100 == 0    -> amount_round_number\n",
"#   (resto)              -> 0\n",
"\n",
"def engineer_features(df: pd.DataFrame) -> pd.DataFrame:\n",
"    \"\"\"Transforma PaySim raw a nuestras 10 features.\n",
"    \n",
"    Cada fila de output es un vector de 10 dimensiones que nuestro\n",
"    MLModelService.predict() va a recibir en produccion.\n",
"    \"\"\"\n",
"    features = pd.DataFrame()\n",
"\n",
"    # 1. AMOUNT: monto bruto\n",
"    # Directo de PaySim, igual que en produccion\n",
"    features[\"amount\"] = df[\"amount\"].astype(float)\n",
"\n",
"    # 2. AMOUNT_VS_USER_AVG: que tan desviado esta del promedio del usuario\n",
"    # PaySim no tiene historial de usuario real. Usamos el balance previo\n",
"    # como proxy: si oldbalanceOrg es 0, no podemos calcular el ratio.\n",
"    # oldbalanceOrg / (amount + 1) nos da una idea de la proporcion.\n",
"    #\n",
"    # En produccion, esto se calcula con el historial real del usuario.\n",
"    old = df[\"oldbalanceOrg\"].astype(float)\n",
"    amt = df[\"amount\"].astype(float)\n",
"    features[\"amount_vs_user_avg\"] = np.where(\n",
"        old > 0,\n",
"        (amt - old) / (old + 1),  # desviacion respecto al saldo previo\n",
"        0.0\n",
"    )\n",
"\n",
"    # 3. AMOUNT_VS_USER_STD: desviacion estandar\n",
"    # Sin historial real, usamos dispersion de todo el dataset\n",
"    # como proxy. No es ideal, pero es un punto de partida.\n",
"    global_std = amt.std()\n",
"    features[\"amount_vs_user_std\"] = np.where(\n",
"        global_std > 0,\n",
"        (amt - amt.mean()) / global_std,\n",
"        0.0\n",
"    )\n",
"\n",
"    # 4 y 5. TX_COUNT: velocidad de transacciones\n",
"    # PaySim no tiene marcas de tiempo reales, solo \"step\" (hora simulada).\n",
"    # Agrupamos por nameOrig y step para estimar velocidad.\n",
"    # Esto es una aproximacion burda pero mejor que 0.\n",
"    velocity = df.groupby([\"nameOrig\", \"step\"]).size().reset_index(name=\"count\")\n",
"    df_with_vel = df.merge(velocity, on=[\"nameOrig\", \"step\"], how=\"left\")\n",
"    features[\"tx_count_last_5min\"] = df_with_vel[\"count\"].fillna(0).astype(float)\n",
"    features[\"tx_count_last_1h\"] = df_with_vel[\"count\"].fillna(0).astype(float)\n",
"\n",
"    # 6. HOUR_OF_DAY: hora del dia\n",
"    # PaySim no tiene timestamp. Usamos step % 24 (cada step = 1 hora).\n",
"    features[\"hour_of_day\"] = (df[\"step\"] % 24).astype(float)\n",
"\n",
"    # 7. IS_WEEKEND: fin de semana\n",
"    # No tenemos dia de la semana real. Dejamos en 0.\n",
"    # En produccion, esto se calcula del timestamp real.\n",
"    features[\"is_weekend\"] = 0.0\n",
"\n",
"    # 8. MERCHANT_RISK_LEVEL: nivel de riesgo del comercio\n",
"    # En PaySim, TRANSFER y CASH_OUT son las operaciones de riesgo\n",
"    # (donde ocurren todos los fraudes). PAYMENT, DEBIT, CASH_IN son seguras.\n",
"    # Mapeamos: TRANSFER/CASH_OUT = riesgo, el resto = seguro.\n",
"    features[\"merchant_risk_level\"] = df[\"type\"].isin([\"TRANSFER\", \"CASH_OUT\"]).astype(float)\n",
"\n",
"    # 9. IS_CRYPTO: es criptomoneda?\n",
"    # PaySim no tiene cripto, pero TRANSFER es la operacion mas cercana\n",
"    # (cambio de dueno sin contraparte comercial registrada).\n",
"    features[\"is_crypto\"] = (df[\"type\"] == \"TRANSFER\").astype(float)\n",
"\n",
"    # 10. AMOUNT_ROUND_NUMBER: monto redondeado\n",
"    # Los montos fraudulentos suelen ser redondos o muy especificos.\n",
"    # Detectar montos multiplo de 1000 es un indicador clasico.\n",
"    features[\"amount_round_number\"] = (\n",
"        (amt > 0) & ((amt % 1000) == 0)\n",
"    ).astype(float)\n",
"\n",
"    return features\n",
"\n",
"\n",
"X = engineer_features(df)\n",
"y = df[\"isFraud\"].values\n",
"\n",
"print(f\"Features generadas: {X.shape[1]}\")\n",
"print(f\"Filas: {X.shape[0]:,}\")\n",
"print(f\"Columnas: {list(X.columns)}\")\n",
"X.head()\n",
])

code([
"# =============================================================================\n",
"# CELDA 6: ANALISIS DE LAS FEATURES GENERADAS\n",
"# =============================================================================\n",
"# Verificamos que las features tengan sentido:\n",
"# - Sin valores nulos\n",
"# - Sin valores infinitos\n",
"# - Distribuciones razonables\n",
"\n",
"print(\"Valores nulos por feature:\")\n",
"print(X.isnull().sum().to_string())\n",
"print(\"\\nValores infinitos por feature:\")\n",
"print(np.isinf(X).sum().to_string())\n",
"\n",
"print(\"\\nEstadisticas descriptivas:\")\n",
"print(X.describe().round(2).to_string())\n",
"\n",
"# Verificacion de balance final\n",
"print(f\"\\nTotal fraudes (y=1): {y.sum():,}\")\n",
"print(f\"Total legitimos (y=0): {len(y) - y.sum():,}\")\n",
"print(f\"Proporcion fraude: {y.mean()*100:.3f}%\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 7: TRAIN/TEST SPLIT + BALANCEO CON SMOTE\n",
"# =============================================================================\n",
"#\n",
"# Por que separar en train y test?\n",
"# Si evaluamos el modelo con los mismos datos que usamos para entrenar,\n",
"# medimos cuan bien MEMORIZO, no cuan bien GENERALIZA. El modelo podria\n",
"# tener 99.9% de accuracy en entrenamiento y 50% en produccion.\n",
"#\n",
"# La regla: NUNCA uses los mismos datos para entrenar y evaluar.\n",
"#\n",
"# Por que SMOTE?\n",
"# Con 0.1% de fraudes, si entrenamos asi nomÃ¡s, el modelo aprende a\n",
"# predecir \"legitimo\" siempre (le da 99.9% de accuracy). SMOTE genera\n",
"# fraudes sinteticos a partir de los fraudes reales para balancear.\n",
"#\n",
"# Como funciona SMOTE:\n",
"# 1. Toma un fraude real\n",
"# 2. Encuentra sus K vecinos mas cercanos (tambien fraudes)\n",
"# 3. Interpola entre ellos para crear un fraude nuevo y realista\n",
"#\n",
"# Visualmente: si tenes 3 fraudes, SMOTE crea puntos intermedios\n",
"# entre ellos. No es magia, es interpolacion lineal en el espacio\n",
"# de features.\n",
"\n",
"# Separamos ANTES de SMOTE para evitar data leakage.\n",
"# Data leakage = contaminar los datos de test con informacion\n",
"# de los datos de train. Si aplicamos SMOTE antes del split,\n",
"# fraudes sinteticos generados de un fraude de train podrian\n",
"# terminar en test, y el modelo tendria \"ayuda\" durante la evaluacion.\n",
"#\n",
"# Orden correcto:\n",
"#   1. Split (train/test)\n",
"#   2. SMOTE solo en TRAIN\n",
"#   3. Evaluacion en TEST (sin SMOTE, con datos REALES)\n",
"\n",
"X_train, X_test, y_train, y_test = train_test_split(\n",
"    X, y,\n",
"    test_size=0.2,        # 20% para test, 80% para train\n",
"    random_state=42,       # Semilla para reproducibilidad\n",
"    stratify=y,            # Mantiene la proporcion de fraudes en ambos sets\n",
")\n",
"\n",
"print(f\"Train: {len(X_train):,} transacciones\")\n",
"print(f\"  - Legitimas: {(y_train == 0).sum():,}\")\n",
"print(f\"  - Fraudes: {(y_train == 1).sum():,} ({y_train.mean()*100:.3f}%)\")\n",
"print(f\"\\nTest: {len(X_test):,} transacciones\")\n",
"print(f\"  - Legitimas: {(y_test == 0).sum():,}\")\n",
"print(f\"  - Fraudes: {(y_test == 1).sum():,} ({y_test.mean()*100:.3f}%)\")\n",
"\n",
"# Aplicamos SMOTE solo en TRAIN\n",
"# sampling_strategy=0.5 significa: generar fraudes hasta que sean\n",
"# el 50% de las legitimos. O sea, si hay 100 legitimos y 1 fraude,\n",
"# SMOTE genera 49 fraudes sinteticos para llegar a 50.\n",
"print(\"\\nAplicando SMOTE en train...\")\n",
"smote = SMOTE(sampling_strategy=0.5, random_state=42)\n",
"X_train_res, y_train_res = smote.fit_resample(X_train, y_train)\n",
"\n",
"print(f\"Train balanceado: {len(X_train_res):,} transacciones\")\n",
"print(f\"  - Legitimas: {(y_train_res == 0).sum():,}\")\n",
"print(f\"  - Fraudes: {(y_train_res == 1).sum():,} ({y_train_res.mean()*100:.1f}%)\")\n",
"\n",
"# Nota importante: SMOTE puede generar outliers. En la vida real,\n",
"# un fraude generado sinteticamente podria no tener sentido logico.\n",
"# Para este proyecto, es aceptable porque PaySim tambien es sintetico.\n",
])

code([
"# =============================================================================\n",
"# CELDA 8: ENTRENAMIENTO DE XGBoost\n",
"# =============================================================================\n",
"#\n",
"# XGBoost = eXtreme Gradient Boosting\n",
"#\n",
"# Concepto: Boosting entrena arboles SECUENCIALMENTE, donde cada arbol\n",
"# nuevo intenta CORREGIR los errores del arbol anterior.\n",
"#\n",
"# Diferencia con Random Forest:\n",
"#   - RF entrena arboles en PARALELO y promedia sus resultados\n",
"#   - XGBoost entrena arboles en SECUENCIA, cada uno aprende de los errores\n",
"#     del anterior (gradient descent sobre arboles)\n",
"#\n",
"# Por que XGBoost para fraude?:\n",
"#   1. Regularizacion L1/L2 -> evita overfitting\n",
"#   2. scale_pos_weight -> maneja imbalance nativamente\n",
"#   3. early_stopping -> deja de entrenar cuando deja de mejorar\n",
"#   4. missing value handling -> acepta nulos sin imputacion\n",
"#   5. Es el algoritmo mas usado en competencias de Kaggle con datos tabulares\n",
"\n",
"# Calculamos scale_pos_weight para balancear las clases\n",
"# Formula: total_negative / total_positive\n",
"# Esto le dice a XGBoost: \"los fraudes son {ratio} veces mas importantes\n",
"# que las legitimos\" — asi el modelo penaliza mas un falso negativo\n",
"# (no detectar un fraude) que un falso positivo (marcar como fraude algo legitimo).\n",
"neg_count = (y_train == 0).sum()\n",
"pos_count = (y_train == 1).sum()\n",
"scale_pos = neg_count / pos_count\n",
"print(f\"scale_pos_weight calculado: {scale_pos:.1f}\")\n",
"print(f\"  (es decir, un error en fraude pesa {scale_pos:.0f}x mas que uno en legitimo)\")\n",
"\n",
"# Configuracion del modelo\n",
"# Cada hiperparametro tiene un proposito:\n",
"model = xgb.XGBClassifier(\n",
"    n_estimators=500,          # Maximo de arboles (early_stopping corta antes)\n",
"    max_depth=6,               # Profundidad de cada arbol (mayor = mas complejo)\n",
"    learning_rate=0.1,         # Tasa de aprendizaje (menor = mas lento pero mejor)\n",
"    subsample=0.8,             # % de muestras por arbol (evita overfitting)\n",
"    colsample_bytree=0.8,      # % de features por arbol (evita overfitting)\n",
"    scale_pos_weight=scale_pos, # Peso de la clase positiva (fraude)\n",
"    eval_metric=\"auc\",         # Metrica de evaluacion: AUC-ROC\n",
"    use_label_encoder=False,    # Deprecado, lo desactivamos\n",
"    random_state=42,           # Reproducibilidad\n",
"    n_jobs=-1,                 # Usa todos los CPUs\n",
")\n",
"\n",
"print(\"\\nEntrenando XGBoost...\")\n",
"print(\"(esto puede tomar 2-5 minutos con 6M de filas)\")\n",
"\n",
"# early_stopping_rounds: si despues de 10 rondas el AUC no mejora,\n",
"# deja de entrenar. Ahorra tiempo y evita overfitting.\n",
"model.fit(\n",
"    X_train_res, y_train_res,\n",
"    eval_set=[(X_test, y_test)],\n",
"    verbose=True,\n",
")\n",
"\n",
"print(\"\\nEntrenamiento completado!\")\n",
"print(f\"Mejor iteracion: {model.best_iteration if hasattr(model, 'best_iteration') else 'N/A'}\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 9: EVALUACION DEL MODELO\n",
"# =============================================================================\n",
"#\n",
"# Evaluamos el modelo con los datos de TEST (nunca vistos durante entrenamiento).\n",
"# Recordar: las metricas importantes son RECALL (detectar fraudes) y\n",
"# luego PRECISION (no tener falsas alarmas).\n",
"\n",
"y_pred = model.predict(X_test)\n",
"y_proba = model.predict_proba(X_test)[:, 1]  # Probabilidad de ser fraude\n",
"\n",
"print(\"=\" * 60)\n",
"print(\"CLASSIFICATION REPORT\")\n",
"print(\"=\" * 60)\n",
"print(classification_report(y_test, y_pred, target_names=[\"Legitimo\", \"Fraude\"]))\n",
"\n",
"print(\"=\" * 60)\n",
"print(\"MATRIZ DE CONFUSION\")\n",
"print(\"=\" * 60)\n",
"tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()\n",
"print(f\"                 Predicho Legitimo   Predicho Fraude\")\n",
"print(f\"Real Legitimo        {tn:>8,}              {fp:>8,}\")\n",
"print(f\"Real Fraude          {fn:>8,}              {tp:>8,}\")\n",
"print()\n",
"print(f\"True Positives (fraude detectado): {tp:,}\")\n",
"print(f\"False Positives (falsa alarma):    {fp:,}\")\n",
"print(f\"False Negatives (fraude no visto): {fn:,}\")\n",
"print(f\"True Negatives (legitimo correcto): {tn:,}\")\n",
"print()\n",
"print(f\"Recall (fraudes detectados): {tp / (tp + fn):.2%}\")\n",
"print(f\"Precision: {tp / (tp + fp):.2%}\")\n",
"print(f\"F1-score: {f1_score(y_test, y_pred):.4f}\")\n",
"print(f\"AUC-ROC: {roc_auc_score(y_test, y_proba):.4f}\")\n",
"\n",
"# Interpretacion:\n",
"# - Recall alto > 90%: detectamos casi todos los fraudes. GENIAL.\n",
"# - Si Precision es baja (muchos FP): el equipo de operaciones recibe\n",
"#   muchas alertas falsas. Se cansan y empiezan a ignorar el sistema.\n",
"# - F1 > 0.80: balance saludable.\n",
"# - AUC > 0.95: el modelo separa muy bien las clases.\n",
])

code([
"# =============================================================================\n",
"# CELDA 10: AJUSTE DEL UMBRAL DE DECISION\n",
"# =============================================================================\n",
"#\n",
"# XGBoost devuelve una probabilidad (0 a 1). Por defecto, clasifica como\n",
"# fraude si proba > 0.5. Pero en deteccion de fraude, 0.5 rara vez es optimo.\n",
"#\n",
"# Podemos ajustar el UMBRAL para priorizar:\n",
"#   - Umbral BAJO (ej: 0.3): detectamos MAS fraudes (mejor recall)\n",
"#     pero generamos MAS falsas alarmas (peor precision)\n",
"#   - Umbral ALTO (ej: 0.8): detectamos MENOS fraudes (peor recall)\n",
"#     pero las alertas son MAS confiables (mejor precision)\n",
"#\n",
"# Donde poner el umbral depende del negocio:\n",
"#   - Si cada fraude cuesta $10,000 -> umbral BAJO (queremos detectar todo)\n",
"#   - Si cada alerta la revisa un humano -> umbral MEDIO\n",
"#   - Si el sistema bloquea automaticamente -> umbral ALTO\n",
"\n",
"from sklearn.metrics import precision_recall_curve\n",
"\n",
"precisions, recalls, thresholds = precision_recall_curve(y_test, y_proba)\n",
"\n",
"print(\"PRECISION Y RECALL POR UMBRAL:\")\n",
"print(f\"{'Umbral':>8} {'Precision':>12} {'Recall':>10} {'F1':>8}\")\n",
"print(\"-\" * 42)\n",
"\n",
"best_f1 = 0\n",
"best_threshold = 0.5\n",
"for i in range(0, len(thresholds), max(1, len(thresholds) // 20)):\n",
"    t = thresholds[i]\n",
"    p = precisions[i]\n",
"    r = recalls[i]\n",
"    f1 = 2 * p * r / (p + r) if (p + r) > 0 else 0\n",
"    if f1 > best_f1:\n",
"        best_f1 = f1\n",
"        best_threshold = t\n",
"    print(f\"{t:>8.3f} {p:>12.4f} {r:>10.4f} {f1:>8.4f}\")\n",
"\n",
"print(f\"\\nMejor umbral por F1: {best_threshold:.3f} (F1={best_f1:.4f})\")\n",
"print(f\"Umbral default (0.5): F1={f1_score(y_test, y_pred):.4f}\")\n",
"\n",
"# En produccion, usaremos la probabilidad CRUDA como score 0-100.\n",
"# El umbral de decision lo manejara el Ensemble segun los tiers de amount.\n",
"# Esto nos da mas flexibilidad que un unico umbral binario.\n",
])

code([
"# =============================================================================\n",
"# CELDA 11: FEATURE IMPORTANCE - Que features importan mas?\n",
"# =============================================================================\n",
"# XGBoost nos dice que features fueron mas importantes para la decision.\n",
"# Esto es CLAVE para:\n",
"#   1. Explicar el modelo a stakeholders\n",
"#   2. Saber si podemos simplificar (features con peso 0)\n",
"#   3. Detectar si el modelo aprendio algo que no deberia\n",
"\n",
"importances = model.feature_importances_\n",
"feature_names = list(X.columns)\n",
"ranking = sorted(zip(feature_names, importances), key=lambda x: x[1], reverse=True)\n",
"\n",
"print(\"FEATURE IMPORTANCE:\")\n",
"print(f\"{'Feature':<25} {'Importancia':>12}\")\n",
"print(\"-\" * 37)\n",
"for name, imp in ranking:\n",
"    bars = \"#\" * int(imp * 50)\n",
"    print(f\"{name:<25} {imp:>10.4f}  {bars}\")\n",
"print()\n",
"\n",
"# Analisis rapido:\n",
"# - Si merchan_risk_level e is_crypto tienen mucha importancia:\n",
"#     el modelo aprendio que TRANSFER/CASH_OUT = fraude. Tiene sentido.\n",
"# - Si amount_round_number importa:\n",
"#     los montos redondos son indicadores de fraude.\n",
"# - Si hour_of_day importa poco:\n",
"#     puede ser porque step%24 no es un buen proxy de hora real.\n",
])

code([
"# =============================================================================\n",
"# CELDA 12: GUARDAR EL MODELO EN FORMATO .joblib\n",
"# =============================================================================\n",
"# Guardamos el modelo para que nuestro sistema de produccion lo cargue.\n",
"# El formato .joblib es mas eficiente que pickle para grandes arrays numpy.\n",
"#\n",
"# En produccion, MLModelService.predict() va a:\n",
"#   1. Cargar este .joblib\n",
"#   2. Recibir features del FeatureEngine\n",
"#   3. Llamar model.predict_proba(features)[:, 1] -> probabilidad\n",
"#   4. Convertir probabilidad a score 0-100\n",
"#   5. Devolver ese score al ensemble\n",
"\n",
"model_path = r\"..\\models\\xgboost_paysim_v1.joblib\"\n",
"joblib.dump(model, model_path)\n",
"print(f\"Modelo guardado en: {model_path}\")\n",
"\n",
"# Verificacion: cargar el modelo y hacer una prediccion de prueba\n",
"loaded = joblib.load(model_path)\n",
"test_sample = X_test[:1]\n",
"pred = loaded.predict_proba(test_sample)[0, 1]\n",
"print(f\"Prediccion de prueba: {pred:.4f} (score ML: {pred*100:.1f}/100)\")\n",
"print()\n",
"print(\"Resumen final:\")\n",
"print(f\"  - Modelo: XGBoost con {model.n_estimators} arboles\")\n",
"print(f\"  - Features: {len(feature_names)} dimensiones\")\n",
"print(f\"  - AUC-ROC: {roc_auc_score(y_test, y_proba):.4f}\")\n",
"print(f\"  - Recall (umbral 0.5): {tp / (tp + fn):.2%}\")\n",
"print(f\"  - Archivo: {model_path}\")\n",
])

# =============================================================================
# NOTAS FINALES
# =============================================================================

md([
"---\n",
"\n",
"## Proximos pasos\n",
"\n",
"1. **Integrar en el API**: Modificar `src/api/v1/transactions.py` para que\n",
"   use este modelo en vez de `ml_score = 0.0`.\n",
"\n",
"2. **Adaptar el FeatureEngine**: Modificar `src/services/feature_engine.py`\n",
"   para que acepte tanto el formato de produccion como el formato de PaySim\n",
"   (o crear un `FeatureEnginePaysim` separado).\n",
"\n",
"3. **Reentrenar con datos reales**: Cuando el sistema acumule suficientes\n",
"   transacciones reales con decisiones de analistas, reentrenar XGBoost\n",
"   con esos datos (que seran de tu dominio especifico).\n",
"\n",
"4. **Ajustar pesos del ensemble**: En `config.py`, cambiar\n",
"   `ensemble_ml_weight=0.10` por un valor mayor (ej. 0.25) si el\n",
"   XGBoost demuestra buena precision.\n",
"\n",
"---\n",
"\n",
"## Glosario rapido\n",
"\n",
"| Termino | Significado |\n",
"|---------|-------------|\n",
"| **XGBoost** | Gradient boosting con regularizacion. Estado del arte en tabular. |\n",
"| **SMOTE** | Genera ejemplos sinteticos de la clase minoritaria para balancear. |\n",
"| **Recall** | De los fraudes reales, cuantos detectamos. Prioridad #1. |\n",
"| **Precision** | De los que marcamos fraude, cuantos acierto. |\n",
"| **AUC-ROC** | Probabilidad de que el modelo rankee un fraude mas alto que uno legitimo. |\n",
"| **Feature importance** | Que tanto contribuye cada feature a la decision del modelo. |\n",
"| **Early stopping** | Deja de entrenar si la metrica no mejora tras N rondas. |\n",
"| **scale_pos_weight** | Peso extra para la clase minoritaria. |\n",
])

# =============================================================================
# ESCRIBIR NOTEBOOK
# =============================================================================

notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.11.0"
        }
    },
    "cells": cells,
}

output_path = r"C:\Users\mikel\Documents\fraud-detector\fraud-detector\notebooks\01-paysim-fraud-detection.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Notebook generado: {output_path}")
