"""Regenerate the case-study playground score bins from the CURRENT artifact.

Writes case-study/assets/data/score-bins.js — the dataset consumed by the
interactive threshold-policy playground (case-study/script.js, ch-05).

The previous file binned ml_score over [0, 100] in 2.5-point steps. Because
the production cubic-smoothing curve compresses scores into roughly
[26, 74], all legitimate mass collapsed into ONE bin and all fraud mass into
ANOTHER — the flagship histogram rendered two lonely bars plus 38 empty ones.
This generator zooms to the meaningful range [20, 80] with 2-point bins so
the actual class spread is visible, while keeping the same data contract:
    const SCORE_BINS = { edges: [...], legit: [...], fraud: [...], meta: {...} }

The scoring path mirrors scripts/generate_case_study_charts.py exactly
(production FeatureEngine + saved calibrated artifact + cubic smoothing), so
these bars describe the same distribution as score-distribution.png.

Usage (from repo root):
    .venv\\Scripts\\python.exe scripts/generate_score_bins.py
"""

import json
import sys
from pathlib import Path

import joblib
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.train_xgboost_aligned import (  # noqa: E402
    add_realistic_noise,
    build_feature_vectors,
    build_synthetic_history,
    load_synthetic_data,
)

MODEL_PATH = "models/xgboost_paysim_v1.joblib"
DATA_SYNTHETIC = "data/synthetic_transactions.csv"
OUT_PATH = Path("case-study/assets/data/score-bins.js")

BIN_LO = 20.0
BIN_HI = 80.0
N_BINS = 30  # 2-point granularity


def cubic_smooth(probabilities: np.ndarray) -> np.ndarray:
    """Production serving transform (MLModelService.predict)."""
    s = 0.5 + 0.7 * (probabilities - 0.5) ** 3 + 0.3 * (probabilities - 0.5)
    return np.clip(s, 0.0, 1.0)


def main() -> None:
    synth_tx, y = load_synthetic_data(DATA_SYNTHETIC)
    histories = [build_synthetic_history(tx) for tx in synth_tx]
    noisy_tx, y = add_realistic_noise(synth_tx, y, fraud_noise_intensity=0.40)
    print("Extracting aligned features with production FeatureEngine...")
    X = build_feature_vectors([{"tx": tx, "history": h} for tx, h in zip(noisy_tx, histories)])

    raw = joblib.load(MODEL_PATH)
    model = raw["model"] if isinstance(raw, dict) else raw
    scores = cubic_smooth(model.predict_proba(X)[:, 1]) * 100.0

    edges = np.linspace(BIN_LO, BIN_HI, N_BINS + 1)
    legit_counts, _ = np.histogram(scores[y == 0], bins=edges)
    fraud_counts, _ = np.histogram(scores[y == 1], bins=edges)

    data = {
        "edges": [round(float(e), 1) for e in edges],
        "legit": [int(c) for c in legit_counts],
        "fraud": [int(c) for c in fraud_counts],
        "meta": {
            "legitN": int((y == 0).sum()),
            "fraudN": int((y == 1).sum()),
            "range": [BIN_LO, BIN_HI],
            "bins": N_BINS,
            "model": MODEL_PATH,
            "dataset": DATA_SYNTHETIC,
        },
    }

    payload = json.dumps(data, separators=(",", ":"))
    OUT_PATH.write_text(
        "// REAL precomputed score distribution — generated by scripts/generate_score_bins.py\n"
        "// from models/xgboost_paysim_v1.joblib over data/synthetic_transactions.csv via\n"
        "// the production FeatureEngine and serving cubic-smoothing. Zoomed to the\n"
        "// meaningful range [" f"{BIN_LO:g}" ", " f"{BIN_HI:g}"
        "] (2-point bins); do not edit by hand.\n"
        f"const SCORE_BINS={payload};\n",
        encoding="utf-8",
    )

    total_legit = int(sum(data["legit"]))
    total_fraud = int(sum(data["fraud"]))
    nonzero_legit = sum(1 for c in data["legit"] if c > 0)
    nonzero_fraud = sum(1 for c in data["fraud"] if c > 0)
    outside = int(((scores < BIN_LO) | (scores > BIN_HI)).sum())
    print(f"wrote {OUT_PATH}")
    print(f"bins={N_BINS} range=[{BIN_LO:g}, {BIN_HI:g}]")
    print(f"legit: {total_legit:,}/{data['meta']['legitN']:,} in-range across {nonzero_legit} nonzero bins")
    print(f"fraud: {total_fraud:,}/{data['meta']['fraudN']:,} in-range across {nonzero_fraud} nonzero bins")
    print(f"scores outside range: {outside:,} of {len(scores):,}")
    print(json.dumps({"nonzero_bins_legit": nonzero_legit, "nonzero_bins_fraud": nonzero_fraud}))


if __name__ == "__main__":
    main()
