"""Genera el notebook 01-paysim-fraud-detection.ipynb con explicaciones didacticas y graficos."""
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

cells = []

def md(source):
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [s if s.endswith("\n") else s + "\n" for s in source]
    })

def code(source):
    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [s if s.endswith("\n") else s + "\n" for s in source]
    })

# =============================================================================
# CELDAS
# =============================================================================

md([
"# Deteccion de Fraude con PaySim + XGBoost\n",
"\n",
"> **Objetivo:** Entrenar un modelo supervisado de clasificacion binaria que detecte\n",
"> transacciones fraudulentas usando el dataset PaySim.\n",
">\n",
"> **Output:** Un archivo `.joblib` que nuestro sistema de produccion cargara para\n",
"> calcular `ml_score` en cada transaccion.\n",
"\n",
"---\n",
"\n",
"## Que vamos a hacer y por que?\n",
"\n",
"Nuestro sistema de deteccion de fraude tiene 3 capas:\n",
"\n",
"| Capa | Estado |\n",
"|------|--------|\n",
"| **Rule Engine** (6 reglas deterministas) | Ya funciona |\n",
"| **XGBoost** (ML supervisado) | Lo vamos a crear aqui |\n",
"| **Ensemble** (combina ambas) | Ya funciona |\n",
"\n",
"Hasta ahora `ml_score` estaba en 0 porque no teniamos modelo. Con PaySim vamos a\n",
"entrenar un **XGBoost clasificador** que aprenda a distinguir transacciones\n",
"fraudulentas de las normales.\n",
"\n",
"---\n",
"\n",
"## Que es PaySim?\n",
"\n",
"PaySim es un simulador de transacciones financieras mobile. Genera datos sinteticos\n",
"realistas basados en una muestra de transacciones reales de una empresa de finanzas\n",
"mobile de Africa.\n",
"\n",
"- **Tamano:** ~6 millones de transacciones\n",
"- **Fraudes:** ~0.1% (muy desbalanceado, como en la vida real)\n",
"- **Columnas:** interpretables (no PCA)\n",
"\n",
"| Columna | Significado |\n",
"|---------|-------------|\n",
"| `step` | Unidad de tiempo (1 step = 1 hora) |\n",
"| `type` | Tipo: PAYMENT, TRANSFER, CASH_OUT, DEBIT, CASH_IN |\n",
"| `amount` | Monto de la transaccion |\n",
"| `nameOrig` | ID del cliente que origina |\n",
"| `oldbalanceOrg` | Saldo del cliente ANTES de la transaccion |\n",
"| `newbalanceOrig` | Saldo del cliente DESPUES de la transaccion |\n",
"| `nameDest` | ID del destinatario |\n",
"| `oldbalanceDest` | Saldo del destinatario ANTES |\n",
"| `newbalanceDest` | Saldo del destinatario DESPUES |\n",
"| **`isFraud`** | **1 = fraude, 0 = legitimo (nuestro TARGET)** |\n",
"| `isFlaggedFraud` | 1 si el sistema ya lo marco (no lo usamos) |\n",
"\n",
"---\n",
"\n",
"## Arquitectura del modelo\n",
"\n",
"```\n",
"PaySim (raw) -> Feature Engineering -> SMOTE -> XGBoost -> .joblib\n",
"                                                       -> MLModelService.predict()\n",
"```\n",
"\n",
"---\n",
"\n",
"## Metricas que nos importan\n",
"\n",
"En deteccion de fraude, **no nos sirve el accuracy**. Si el 99.9% de las\n",
"transacciones son legitimas, un modelo que siempre diga \"legitimo\" tiene 99.9%\n",
"de accuracy pero no detecta NINGUN fraude.\n",
"\n",
"| Metrica | Por que importa |\n",
"|---------|-----------------|\n",
"| **Recall** | De todos los fraudes reales, cuantos detectamos? **Lo mas critico** |\n",
"| **Precision** | De los que marcamos como fraude, cuantos lo eran realmente? |\n",
"| **F1** | Balance entre precision y recall |\n",
"| **AUC-ROC** | Capacidad del modelo de separar clases |\n",
"| **Matriz de confusion** | Ver TP, FP, FN, TN |\n",
"\n",
"---\n",
])

code([
"# =============================================================================\n",
"# CELDA 1: IMPORTS Y CONFIGURACION\n",
"# =============================================================================\n",
"# Por que estos imports?:\n",
"#   - pandas: manipular el CSV como tabla\n",
"#   - numpy: operaciones matematicas rapidas\n",
"#   - matplotlib + seaborn: visualizacion. El ojo humano procesa un grafico\n",
"#     en milisegundos, una tabla de numeros requiere minuto de lectura.\n",
"#   - train_test_split: separar datos en entrenamiento y prueba\n",
"#   - SMOTE: genera ejemplos sinteticos de la clase minoritaria\n",
"#   - XGBoost: gradient boosting con regularizacion. Estado del arte tabular.\n",
"#   - joblib: guardar/cargar el modelo\n",
"\n",
"import pandas as pd\n",
"import numpy as np\n",
"import matplotlib.pyplot as plt\n",
"import seaborn as sns\n",
"\n",
"from sklearn.model_selection import train_test_split\n",
"from sklearn.metrics import (\n",
"    classification_report,\n",
"    confusion_matrix,\n",
"    roc_auc_score,\n",
"    roc_curve,\n",
"    precision_recall_curve,\n",
"    f1_score,\n",
")\n",
"from imblearn.over_sampling import SMOTE\n",
"import xgboost as xgb\n",
"import joblib\n",
"import warnings\n",
"warnings.filterwarnings('ignore')\n",
"\n",
"# Configuracion global de graficos\n",
"# Un estilo limpio y profesional para que los graficos sean presentables\n",
"sns.set_theme(style=\"whitegrid\", palette=\"viridis\")\n",
"plt.rcParams.update({\n",
"    \"figure.figsize\": (10, 5),\n",
"    \"font.size\": 11,\n",
"})\n",
"\n",
"print(\"Imports cargados correctamente\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 2: CARGA DEL DATASET\n",
"# =============================================================================\n",
"\n",
"PATH = r\"..\\transaccion\\PS_20174392719_1491204439457_log.csv\"\n",
"\n",
"df = pd.read_csv(PATH)\n",
"print(f\"Filas: {df.shape[0]:,}\")\n",
"print(f\"Columnas: {df.shape[1]}\")\n",
"print(f\"Memoria estimada: {df.memory_usage(deep=True).sum() / 1024**2:.1f} MB\")\n",
"df.head(3)\n",
])

code([
"# =============================================================================\n",
"# CELDA 3: ANALISIS EXPLORATORIO (EDA)\n",
"# =============================================================================\n",
"\n",
"print(\"=\" * 50)\n",
"print(\"DISTRIBUCION DE CLASES (isFraud)\")\n",
"print(\"=\" * 50)\n",
"fraud_counts = df[\"isFraud\"].value_counts()\n",
"fraud_pct = df[\"isFraud\"].value_counts(normalize=True) * 100\n",
"for label in [0, 1]:\n",
"    print(f\"  {label}: {fraud_counts[label]:>8,} tx ({fraud_pct[label]:.3f}%)\")\n",
"print(f\"\\nProporcion: 1 fraude por cada {fraud_counts[0] // fraud_counts[1]:,} legitimas\")\n",
"\n",
"print(\"\\n\" + \"=\" * 50)\n",
"print(\"TIPOS DE OPERACION\")\n",
"print(\"=\" * 50)\n",
"print(df[\"type\"].value_counts().to_string())\n",
"\n",
"print(\"\\n\" + \"=\" * 50)\n",
"print(\"FRAUDES POR TIPO DE OPERACION\")\n",
"print(\"=\" * 50)\n",
"print(df[df[\"isFraud\"] == 1][\"type\"].value_counts().to_string())\n",
"print(\"\\n(Insight: los fraudes solo ocurren en TRANSFER y CASH_OUT)\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 4: VISUALIZACION EDA\n",
"# =============================================================================\n",
"# Los graficos transmiten informacion que las tablas no pueden.\n",
"# Este grafico muestra de un vistazo:\n",
"#   - Que tan desbalanceado es el dataset\n",
"#   - Que tipos de operacion existen y su volumen\n",
"#   - Donde se concentran los fraudes\n",
"\n",
"fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
"fig.suptitle(\"Analisis Exploratorio - PaySim\", fontsize=16, fontweight=\"bold\")\n",
"\n",
"# Grafico 1: Balance de clases (arriba izquierda)\n",
"# Por que es importante: visualizar el desbalance te graba a fuego\n",
"# por que el accuracy no sirve. El ojo ve una barra enorme vs una\n",
"# casi invisible y entiende el problema al instante.\n",
"ax1 = axes[0, 0]\n",
"colors = [\"#2ecc71\", \"#e74c3c\"]\n",
"bars = ax1.bar([\"Legitimo (0)\", \"Fraude (1)\"], fraud_counts.values, color=colors, edgecolor=\"white\")\n",
"for bar, val in zip(bars, fraud_counts.values):\n",
"    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 50000,\n",
"            f\"{val:,}\", ha=\"center\", fontweight=\"bold\")\n",
"ax1.set_ylabel(\"Cantidad de transacciones\")\n",
"ax1.set_title(\"Distribucion de Clases\", fontweight=\"bold\")\n",
"\n",
"# Grafico 2: Tipos de operacion (arriba derecha)\n",
"ax2 = axes[0, 1]\n",
"type_counts = df[\"type\"].value_counts()\n",
"bars2 = ax2.bar(type_counts.index, type_counts.values, color=\"#3498db\", edgecolor=\"white\")\n",
"for bar, val in zip(bars2, type_counts.values):\n",
"    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 50000,\n",
"            f\"{val:,}\", ha=\"center\", rotation=45)\n",
"ax2.set_ylabel(\"Cantidad\")\n",
"ax2.set_title(\"Transacciones por Tipo\", fontweight=\"bold\")\n",
"ax2.tick_params(axis=\"x\", rotation=45)\n",
"\n",
"# Grafico 3: Fraud boxplot (abajo izquierda)\n",
"# El boxplot muestra la distribucion: mediana, cuartiles, outliers.\n",
"# Aca vemos si los montos de fraude se diferencian de los legitimos.\n",
"ax3 = axes[1, 0]\n",
"sns.boxplot(data=df, x=\"isFraud\", y=\"amount\", ax=ax3, palette=colors)\n",
"ax3.set_xticklabels([\"Legitimo\", \"Fraude\"])\n",
"ax3.set_title(\"Distribucion de Montos por Clase\", fontweight=\"bold\")\n",
"ax3.set_ylabel(\"Monto\")\n",
"\n",
"# Grafico 4: Fraudes por tipo (abajo derecha)\n",
"ax4 = axes[1, 1]\n",
"fraud_by_type = df[df[\"isFraud\"] == 1][\"type\"].value_counts()\n",
"bars4 = ax4.bar(fraud_by_type.index, fraud_by_type.values, color=\"#e74c3c\", edgecolor=\"white\")\n",
"for bar, val in zip(bars4, fraud_by_type.values):\n",
"    ax4.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 100,\n",
"            f\"{val:,}\", ha=\"center\")\n",
"ax4.set_title(\"Fraudes por Tipo de Operacion\", fontweight=\"bold\")\n",
"ax4.set_ylabel(\"Cantidad de fraudes\")\n",
"\n",
"plt.tight_layout()\n",
"plt.show()\n",
"\n",
"print(\"Conclusion visual de EDA:\")\n",
"print(\"  - 99.9% de los datos son legitimos (desbalance extremo)\")\n",
"print(\"  - Solo TRANSFER y CASH_OUT tienen fraudes\")\n",
"print(\"  - Los montos de fraude tienden a ser mas altos\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 5: VERIFICACION DE CONSISTENCIA\n",
"# =============================================================================\n",
"\n",
"fraudes = df[df[\"isFraud\"] == 1]\n",
"print(f\"Total fraudes: {len(fraudes)}\")\n",
"print(f\"  - TRANSFER: {len(fraudes[fraudes['type'] == 'TRANSFER'])}\")\n",
"print(f\"  - CASH_OUT: {len(fraudes[fraudes['type'] == 'CASH_OUT'])}\")\n",
"\n",
"# Regla del saldo: en fraudes TRANSFER, el saldo origen se vacia\n",
"org_balance_check = (\n",
"    fraudes[fraudes[\"type\"] == \"TRANSFER\"][\"oldbalanceOrg\"]\n",
"    == fraudes[fraudes[\"type\"] == \"TRANSFER\"][\"amount\"]\n",
").mean()\n",
"print(f\"\\nFraudes TRANSFER donde oldbalanceOrg == amount: {org_balance_check:.1%}\")\n",
"\n",
"# Regla del destino: en fraudes, el destino suele ser 0 (cuenta nueva)\n",
"dest_zero_check = (fraudes[\"oldbalanceDest\"] == 0).mean()\n",
"print(f\"Fraudes donde oldbalanceDest == 0 (cuenta nueva): {dest_zero_check:.1%}\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 6: FEATURE ENGINEERING\n",
"# =============================================================================\n",
"\n",
"def engineer_features(df: pd.DataFrame) -> pd.DataFrame:\n",
"    \"\"\"Transforma PaySim raw a nuestras 10 features.\"\"\"\n",
"    features = pd.DataFrame()\n",
"\n",
"    # 1. AMOUNT\n",
"    features[\"amount\"] = df[\"amount\"].astype(float)\n",
"\n",
"    # 2. AMOUNT_VS_USER_AVG\n",
"    old = df[\"oldbalanceOrg\"].astype(float)\n",
"    amt = df[\"amount\"].astype(float)\n",
"    features[\"amount_vs_user_avg\"] = np.where(\n",
"        old > 0,\n",
"        (amt - old) / (old + 1),\n",
"        0.0\n",
"    )\n",
"\n",
"    # 3. AMOUNT_VS_USER_STD\n",
"    global_std = amt.std()\n",
"    features[\"amount_vs_user_std\"] = np.where(\n",
"        global_std > 0,\n",
"        (amt - amt.mean()) / global_std,\n",
"        0.0\n",
"    )\n",
"\n",
"    # 4 y 5. TX_COUNT\n",
"    velocity = df.groupby([\"nameOrig\", \"step\"]).size().reset_index(name=\"count\")\n",
"    df_with_vel = df.merge(velocity, on=[\"nameOrig\", \"step\"], how=\"left\")\n",
"    features[\"tx_count_last_5min\"] = df_with_vel[\"count\"].fillna(0).astype(float)\n",
"    features[\"tx_count_last_1h\"] = df_with_vel[\"count\"].fillna(0).astype(float)\n",
"\n",
"    # 6. HOUR_OF_DAY\n",
"    features[\"hour_of_day\"] = (df[\"step\"] % 24).astype(float)\n",
"\n",
"    # 7. IS_WEEKEND\n",
"    features[\"is_weekend\"] = 0.0\n",
"\n",
"    # 8. MERCHANT_RISK_LEVEL\n",
"    features[\"merchant_risk_level\"] = df[\"type\"].isin([\"TRANSFER\", \"CASH_OUT\"]).astype(float)\n",
"\n",
"    # 9. IS_CRYPTO\n",
"    features[\"is_crypto\"] = (df[\"type\"] == \"TRANSFER\").astype(float)\n",
"\n",
"    # 10. AMOUNT_ROUND_NUMBER\n",
"    features[\"amount_round_number\"] = (\n",
"        (amt > 0) & ((amt % 1000) == 0)\n",
"    ).astype(float)\n",
"\n",
"    return features\n",
"\n",
"\n",
"X = engineer_features(df)\n",
"y = df[\"isFraud\"].values\n",
"\n",
"print(f\"Features generadas: {X.shape[1]}\")\n",
"print(f\"Filas: {X.shape[0]:,}\")\n",
"print(f\"Columnas: {list(X.columns)}\")\n",
"X.head()\n",
])

code([
"# =============================================================================\n",
"# CELDA 7: ANALISIS DE LAS FEATURES\n",
"# =============================================================================\n",
"\n",
"print(\"Valores nulos por feature:\")\n",
"print(X.isnull().sum().to_string())\n",
"print(\"\\nValores infinitos por feature:\")\n",
"print(np.isinf(X).sum().to_string())\n",
"print(\"\\nEstadisticas descriptivas:\")\n",
"print(X.describe().round(2).to_string())\n",
"\n",
"print(f\"\\nTotal fraudes (y=1): {y.sum():,}\")\n",
"print(f\"Total legitimos (y=0): {len(y) - y.sum():,}\")\n",
"print(f\"Proporcion fraude: {y.mean()*100:.3f}%\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 8: CORRELACION ENTRE FEATURES\n",
"# =============================================================================\n",
"# El mapa de calor de correlacion muestra que features estan relacionadas.\n",
"# Sirve para:\n",
"#   1. Detectar features redundantes (correlacion > 0.9)\n",
"#   2. Entender relaciones entre variables (ej: amount y amount_vs_user_avg)\n",
"#   3. Identificar posibles problemas de multicolinealidad\n",
"#\n",
"# XGBoost es robusto a multicolinealidad (a diferencia de regresion lineal),\n",
"# pero igual es util entender las relaciones.\n",
"\n",
"plt.figure(figsize=(12, 8))\n",
"corr = X.corr()\n",
"mask = np.triu(np.ones_like(corr, dtype=bool))  # Solo mitad inferior\n",
"\n",
"sns.heatmap(\n",
"    corr, mask=mask, annot=True, fmt=\".2f\",\n",
"    cmap=\"RdBu_r\", center=0, square=True,\n",
"    linewidths=0.5, cbar_kws={\"shrink\": 0.8}\n",
")\n",
"plt.title(\"Mapa de Calor de Correlacion entre Features\", fontsize=14, fontweight=\"bold\")\n",
"plt.tight_layout()\n",
"plt.show()\n",
"\n",
"# Buscar pares con alta correlacion\n",
"print(\"Pares con correlacion > 0.7:\")\n",
"high_corr = []\n",
"for i in range(len(corr.columns)):\n",
"    for j in range(i):\n",
"        if abs(corr.iloc[i, j]) > 0.7:\n",
"            high_corr.append((corr.columns[i], corr.columns[j], corr.iloc[i, j]))\n",
"if high_corr:\n",
"    for c1, c2, v in high_corr:\n",
"        print(f\"  {c1} <-> {c2}: {v:.2f}\")\n",
"else:\n",
"    print(\"  Ningun par supera 0.7 - buena independencia de features\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 9: TRAIN/TEST SPLIT + SMOTE\n",
"# =============================================================================\n",
"# Orden correcto: split -> SMOTE solo en train.\n",
"# Si hicieramos SMOTE antes del split, los datos sinteticos generados\n",
"# de transacciones de train podrian contaminar el test (data leakage).\n",
"\n",
"X_train, X_test, y_train, y_test = train_test_split(\n",
"    X, y,\n",
"    test_size=0.2,\n",
"    random_state=42,\n",
"    stratify=y,  # Mantiene la misma proporcion de fraude en train y test\n",
")\n",
"\n",
"print(f\"Train: {len(X_train):,} transacciones\")\n",
"print(f\"  - Legitimas: {(y_train == 0).sum():,}\")\n",
"print(f\"  - Fraudes: {(y_train == 1).sum():,} ({y_train.mean()*100:.3f}%)\")\n",
"print(f\"\\nTest: {len(X_test):,} transacciones\")\n",
"print(f\"  - Legitimas: {(y_test == 0).sum():,}\")\n",
"print(f\"  - Fraudes: {(y_test == 1).sum():,} ({y_test.mean()*100:.3f}%)\")\n",
"\n",
"# Aplicamos SMOTE solo en TRAIN\n",
"# sampling_strategy=0.5: despues de SMOTE, las fraudulentas seran\n",
"# el 50% de las legitimas (balance 2:1 en vez de 1000:1)\n",
"print(\"\\nAplicando SMOTE en train...\")\n",
"smote = SMOTE(sampling_strategy=0.5, random_state=42)\n",
"X_train_res, y_train_res = smote.fit_resample(X_train, y_train)\n",
"\n",
"print(f\"Train balanceado: {len(X_train_res):,} transacciones\")\n",
"print(f\"  - Legitimas: {(y_train_res == 0).sum():,}\")\n",
"print(f\"  - Fraudes: {(y_train_res == 1).sum():,} ({y_train_res.mean()*100:.1f}%)\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 10: ENTRENAMIENTO XGBoost\n",
"# =============================================================================\n",
"\n",
"neg_count = (y_train == 0).sum()\n",
"pos_count = (y_train == 1).sum()\n",
"scale_pos = neg_count / pos_count\n",
"print(f\"scale_pos_weight calculado: {scale_pos:.1f}\")\n",
"print(f\"  (un error en fraude pesa {scale_pos:.0f}x mas que uno en legitimo)\")\n",
"\n",
"model = xgb.XGBClassifier(\n",
"    n_estimators=500,\n",
"    max_depth=6,\n",
"    learning_rate=0.1,\n",
"    subsample=0.8,\n",
"    colsample_bytree=0.8,\n",
"    scale_pos_weight=scale_pos,\n",
"    eval_metric=\"auc\",\n",
"    use_label_encoder=False,\n",
"    random_state=42,\n",
"    n_jobs=-1,\n",
")\n",
"\n",
"print(\"\\nEntrenando XGBoost (puede tomar 2-5 minutos)...\")\n",
"model.fit(\n",
"    X_train_res, y_train_res,\n",
"    eval_set=[(X_test, y_test)],\n",
"    verbose=True,\n",
")\n",
"print(\"\\nEntrenamiento completado!\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 11: EVALUACION - Matriz de Confusion Visual\n",
"# =============================================================================\n",
"\n",
"y_pred = model.predict(X_test)\n",
"y_proba = model.predict_proba(X_test)[:, 1]\n",
"\n",
"print(\"=\" * 60)\n",
"print(\"CLASSIFICATION REPORT\")\n",
"print(\"=\" * 60)\n",
"print(classification_report(y_test, y_pred, target_names=[\"Legitimo\", \"Fraude\"]))\n",
"\n",
"# Matriz de confusion como HEATMAP\n",
"# Un heatmap se procesa en 1 segundo. Los numeros sueltos te hacen\n",
"# buscar con el ojo cual es cual. El color te guia al instante:\n",
"#   - Verde oscuro: aciertos (TP, TN)\n",
"#   - Rojo: errores (FP, FN)\n",
"cm = confusion_matrix(y_test, y_pred)\n",
"tn, fp, fn, tp = cm.ravel()\n",
"\n",
"plt.figure(figsize=(6, 5))\n",
"sns.heatmap(\n",
"    cm, annot=True, fmt=\",\", cmap=\"RdYlGn\",\n",
"    xticklabels=[\"Predicho Legitimo\", \"Predicho Fraude\"],\n",
"    yticklabels=[\"Real Legitimo\", \"Real Fraude\"],\n",
"    cbar=False,\n",
")\n",
"plt.title(\"Matriz de Confusion\", fontsize=14, fontweight=\"bold\")\n",
"plt.tight_layout()\n",
"plt.show()\n",
"\n",
"print(f\"True Positives (fraude detectado):  {tp:>8,}\")\n",
"print(f\"False Positives (falsa alarma):     {fp:>8,}\")\n",
"print(f\"False Negatives (fraude no visto):  {fn:>8,}\")\n",
"print(f\"True Negatives (legitimo correcto): {tn:>8,}\")\n",
"print()\n",
"print(f\"Recall  (fraudes detectados): {tp / (tp + fn):.2%}\")\n",
"print(f\"Precision:                     {tp / (tp + fp):.2%}\")\n",
"print(f\"F1-score:                      {f1_score(y_test, y_pred):.4f}\")\n",
"print(f\"AUC-ROC:                       {roc_auc_score(y_test, y_proba):.4f}\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 12: CURVA ROC\n",
"# =============================================================================\n",
"# La curva ROC muestra la relacion entre:\n",
"#   - Tasa de Verdaderos Positivos (TPR): fraudes que detectamos\n",
"#   - Tasa de Falsos Positivos (FPR): legitimas que marcamos mal\n",
"#\n",
"# AUC (Area Under Curve): probabilidad de que el modelo ordene\n",
"# un fraude aleatorio MAS ALTO que una legitima aleatoria.\n",
"# AUC = 1.0: perfecto. AUC = 0.5: aleatorio.\n",
"#\n",
"# En datasets desbalanceados, ROC puede ser optimista.\n",
"# La curva Precision-Recall (siguiente celda) es mas honesta.\n",
"\n",
"fpr, tpr, thresholds_roc = roc_curve(y_test, y_proba)\n",
"auc = roc_auc_score(y_test, y_proba)\n",
"\n",
"plt.figure(figsize=(8, 6))\n",
"plt.plot(fpr, tpr, color=\"#2ecc71\", lw=3, label=f\"XGBoost (AUC = {auc:.4f})\")\n",
"plt.plot([0, 1], [0, 1], \"k--\", lw=1, label=\"Aleatorio (AUC = 0.5)\")\n",
"plt.fill_between(fpr, tpr, alpha=0.15, color=\"#2ecc71\")\n",
"plt.xlim([0.0, 1.0])\n",
"plt.ylim([0.0, 1.05])\n",
"plt.xlabel(\"Tasa de Falsos Positivos (FPR)\", fontsize=12)\n",
"plt.ylabel(\"Tasa de Verdaderos Positivos (TPR)\", fontsize=12)\n",
"plt.title(\"Curva ROC - Receiver Operating Characteristic\", fontsize=14, fontweight=\"bold\")\n",
"plt.legend(loc=\"lower right\")\n",
"plt.grid(alpha=0.3)\n",
"plt.tight_layout()\n",
"plt.show()\n",
"\n",
"print(f\"AUC-ROC: {auc:.4f}\")\n",
"print(\"Interpretacion:\")\n",
"print(f\"  - AUC > 0.95: el modelo separa excelentemente las clases\")\n",
"print(f\"  - AUC > 0.90: muy buen poder discriminativo\")\n",
"print(f\"  - AUC > 0.80: aceptable\")\n",
"print(f\"  - AUC < 0.70: el modelo no discrimina bien\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 13: CURVA PRECISION-RECALL\n",
"# =============================================================================\n",
"# Esta curva es MAS IMPORTANTE que ROC en deteccion de fraude.\n",
"# Por que?: Porque ROC evalua sobre TODAS las transacciones,\n",
"# mientras que PR se enfoca en la clase minoritaria (fraude).\n",
"#\n",
"# En datasets con 99.9% de legitimas, un modelo puede tener AUC=0.98\n",
"# y detectar SOLO el 10% de los fraudes. La curva PR no permite\n",
"# ese engano porque solo mira la clase que nos importa.\n",
"#\n",
"# Cuando la linea esta arriba a la derecha = modelo excelente.\n",
"# Cuando la linea cae rapido = muchos falsos positivos.\n",
"\n",
"precisions, recalls, thresholds_pr = precision_recall_curve(y_test, y_proba)\n",
"\n",
"plt.figure(figsize=(8, 6))\n",
"plt.plot(recalls, precisions, color=\"#e74c3c\", lw=3, label=\"XGBoost\")\n",
"plt.fill_between(recalls, precisions, alpha=0.15, color=\"#e74c3c\")\n",
"plt.xlabel(\"Recall\", fontsize=12)\n",
"plt.ylabel(\"Precision\", fontsize=12)\n",
"plt.xlim([0.0, 1.05])\n",
"plt.ylim([0.0, 1.05])\n",
"plt.title(\"Curva Precision-Recall\", fontsize=14, fontweight=\"bold\")\n",
"plt.legend(loc=\"lower left\")\n",
"plt.grid(alpha=0.3)\n",
"plt.tight_layout()\n",
"plt.show()\n",
"\n",
"print(\"Interpretacion de la curva PR:\")\n",
"print(\"  - Arriba a la derecha: precision y recall altos IDEAL\")\n",
"print(\"  - Caida vertical: a cierto umbral, los FP explotan\")\n",
"print(\"  - El punto de corte optimo depende del negocio\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 14: AJUSTE DEL UMBRAL DE DECISION\n",
"# =============================================================================\n",
"# Donde poner el umbral depende del COSTE de cada error:\n",
"#   - Si un fraude no detectado cuesta 10.000 EUR -> umbral BAJO\n",
"#   - Si cada falso positivo lo revisa un humano -> umbral MEDIO\n",
"#   - Si el sistema bloquea automaticamente -> umbral ALTO\n",
"\n",
"print(\"PRECISION Y RECALL POR UMBRAL:\")\n",
"print(f\"{'Umbral':>8} {'Precision':>12} {'Recall':>10} {'F1':>10}\")\n",
"print(\"-\" * 44)\n",
"\n",
"best_f1 = 0\n",
"best_threshold = 0.5\n",
"for i in range(0, len(thresholds_pr), max(1, len(thresholds_pr) // 20)):\n",
"    t = thresholds_pr[i]\n",
"    p = precisions[i]\n",
"    r = recalls[i]\n",
"    f1 = 2 * p * r / (p + r) if (p + r) > 0 else 0\n",
"    if f1 > best_f1:\n",
"        best_f1 = f1\n",
"        best_threshold = t\n",
"    print(f\"{t:>8.3f} {p:>12.4f} {r:>10.4f} {f1:>10.4f}\")\n",
"\n",
"print(f\"\\nMejor umbral por F1: {best_threshold:.3f} (F1={best_f1:.4f})\")\n",
"print(f\"Umbral default (0.5): F1={f1_score(y_test, y_pred):.4f}\")\n",
"\n",
"# Grafico: Precision y Recall en funcion del umbral\n",
"# Permite ver visualmente donde esta el punto de equilibrio.\n",
"plt.figure(figsize=(10, 5))\n",
"plt.plot(thresholds_pr, precisions[:-1], \"b-\", label=\"Precision\", lw=2)\n",
"plt.plot(thresholds_pr, recalls[:-1], \"r-\", label=\"Recall\", lw=2)\n",
"plt.axvline(x=best_threshold, color=\"green\", linestyle=\"--\",\n",
"            label=f\"Mejor F1 (umbral={best_threshold:.2f})\")\n",
"plt.xlabel(\"Umbral\", fontsize=12)\n",
"plt.ylabel(\"Score\", fontsize=12)\n",
"plt.title(\"Precision y Recall vs Umbral de Decision\", fontsize=14, fontweight=\"bold\")\n",
"plt.legend()\n",
"plt.grid(alpha=0.3)\n",
"plt.tight_layout()\n",
"plt.show()\n",
])

code([
"# =============================================================================\n",
"# CELDA 15: FEATURE IMPORTANCE (GRAFICO)\n",
"# =============================================================================\n",
"# XGBoost nos dice que features fueron mas importantes.\n",
"# El grafico de barras horizontales es el formato mas legible:\n",
"#   - La barra mas larga = la feature que mas influye\n",
"#   - Si alguna feature tiene peso ~0, podriamos eliminarla\n",
"\n",
"importances = model.feature_importances_\n",
"feature_names = list(X.columns)\n",
"ranking = sorted(zip(feature_names, importances), key=lambda x: x[1])\n",
"\n",
"names, values = zip(*ranking)\n",
"\n",
"plt.figure(figsize=(10, 6))\n",
"colors = plt.cm.viridis(np.linspace(0.3, 0.9, len(names)))\n",
"bars = plt.barh(range(len(names)), values, color=colors, edgecolor=\"white\")\n",
"plt.yticks(range(len(names)), names)\n",
"plt.xlabel(\"Importancia\", fontsize=12)\n",
"plt.title(\"Feature Importance - XGBoost\", fontsize=14, fontweight=\"bold\")\n",
"\n",
"# Agregar etiquetas con el valor numerico\n",
"for bar, val in zip(bars, values):\n",
"    plt.text(bar.get_width() + 0.005, bar.get_y() + bar.get_height()/2,\n",
"            f\"{val:.3f}\", va=\"center\", fontsize=10)\n",
"\n",
"plt.tight_layout()\n",
"plt.show()\n",
"\n",
"print(\"\\nRanking de Importancia:\")\n",
"for i, (name, imp) in enumerate(reversed(list(ranking)), 1):\n",
"    print(f\"  {i}. {name}: {imp:.4f}\")\n",
])

code([
"# =============================================================================\n",
"# CELDA 16: GUARDAR MODELO\n",
"# =============================================================================\n",
"\n",
"model_path = r\"..\\models\\xgboost_paysim_v1.joblib\"\n",
"joblib.dump(model, model_path)\n",
"print(f\"Modelo guardado en: {model_path}\")\n",
"\n",
"# Verificacion de carga\n",
"loaded = joblib.load(model_path)\n",
"test_sample = X_test[:1]\n",
"pred = loaded.predict_proba(test_sample)[0, 1]\n",
"print(f\"Prediccion de prueba: {pred:.4f} (score ML: {pred*100:.1f}/100)\")\n",
"print()\n",
"print(\"Resumen final:\")\n",
"print(f\"  - Modelo: XGBoost con {model.n_estimators} arboles\")\n",
"print(f\"  - Features: {len(feature_names)} dimensiones\")\n",
"print(f\"  - AUC-ROC: {roc_auc_score(y_test, y_proba):.4f}\")\n",
"print(f\"  - Recall (umbral 0.5): {tp / (tp + fn):.2%}\")\n",
"print(f\"  - Archivo: {model_path}\")\n",
])

md([
"---\n",
"\n",
"## Proximos pasos\n",
"\n",
"1. **Integrar en el API**: Modificar `src/api/v1/transactions.py` para que\n",
"   use este modelo en vez de `ml_score = 0.0`.\n",
"\n",
"2. **Reentrenar con datos reales**: Cuando el sistema acumule suficientes\n",
"   transacciones reales con decisiones de analistas, reentrenar XGBoost\n",
"   con esos datos.\n",
"\n",
"3. **Ajustar pesos del ensemble**: En `config.py`, cambiar\n",
"   `ensemble_ml_weight=0.10` por un valor mayor (ej. 0.25) si el\n",
"   XGBoost demuestra buena precision.\n",
"\n",
"---\n",
"\n",
"## Glosario rapido\n",
"\n",
"| Termino | Significado |\n",
"|---------|-------------|\n",
"| **XGBoost** | Gradient boosting con regularizacion. Estado del arte en tabular. |\n",
"| **SMOTE** | Genera ejemplos sinteticos de la clase minoritaria para balancear. |\n",
"| **Recall** | De los fraudes reales, cuantos detectamos. Prioridad #1. |\n",
"| **Precision** | De los que marcamos fraude, cuantos acierto. |\n",
"| **AUC-ROC** | Probabilidad de que el modelo rankee un fraude mas alto que uno legitimo. |\n",
"| **Curva PR** | Precision vs Recall. Mas util que ROC en datos desbalanceados. |\n",
"| **Feature importance** | Que tanto contribuye cada feature a la decision. |\n",
"| **Matriz de confusion** | TP, FP, FN, TN en formato visual. |\n",
])

# =============================================================================
# ESCRIBIR NOTEBOOK
# =============================================================================

notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.11.0"
        }
    },
    "cells": cells,
}

# Resolved from the repo root rather than an absolute path. The hardcoded form
# published this contributor's Windows username and home directory in a public
# repository, and broke on every machine but that one.
output_path = str(REPO_ROOT / "notebooks" / "01-paysim-fraud-detection.ipynb")
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Notebook generado: {output_path}")
print(f"Celdas: {len(cells)} ({sum(1 for c in cells if c['cell_type']=='markdown')} markdown + {sum(1 for c in cells if c['cell_type']=='code')} code)")
