"""Round-trip tests for the initial Alembic migration — R4-006.

Proves that ``alembic upgrade head`` creates exactly the table set defined by
``Base.metadata`` and that ``alembic downgrade base`` removes them all.

The project targets PostgreSQL (UUID dialect types), so the round-trip runs on
a scratch SQLite database with a small compile hook rendering PostgreSQL
``UUID`` as ``CHAR(32)``. This verifies the full structural surface of the
migration (tables, columns, PKs, FKs, uniques, indexes). Native-PostgreSQL
rendering is exercised by CI's Postgres service (see audit R3-008, wave 4).
"""

from pathlib import Path

import pytest
from alembic.config import Config
from sqlalchemy import create_engine
from sqlalchemy import inspect as sa_inspect
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.ext.compiler import compiles

from alembic import command
from src.core.config import Settings
from src.models.base import Base

# Import for side effects: every model must be registered on Base.metadata
# before the expected table set is derived from it.
import src.models  # noqa: F401,E402

PROJECT_ROOT = Path(__file__).resolve().parents[2]
ALEMBIC_INI = PROJECT_ROOT / "alembic.ini"
MIGRATION_FILE = PROJECT_ROOT / "alembic" / "versions" / "b02e4753e78e_initial.py"

# Derived from the ORM metadata on purpose: the invariant this file protects is
# "migrations produce exactly the tables the models declare". A hardcoded list
# silently rots every time a model + migration pair is added, which previously
# hid the drift_reference_data table.
EXPECTED_TABLES = set(Base.metadata.tables)


@compiles(PG_UUID, "sqlite")
def _render_pg_uuid_on_sqlite(type_, compiler, **kw):
    """Render PostgreSQL UUID as CHAR(32) so migrations can run on SQLite."""
    return "CHAR(32)"


@pytest.fixture()
def scratch_db_url(tmp_path):
    """SQLite scratch DB URL wired into alembic env via settings override."""
    url = f"sqlite:///{tmp_path / 'scratch.db'}"
    original = Settings.database_url
    Settings.database_url = property(lambda self: url)  # type: ignore[method-assign]
    try:
        yield url
    finally:
        Settings.database_url = original  # type: ignore[method-assign]


@pytest.fixture()
def alembic_config(scratch_db_url):
    # Build the config without an INI file so alembic never calls
    # fileConfig(), which reconfigures process-wide logging with
    # disable_existing_loggers=True and breaks caplog-based assertions
    # in any test running later in the same session.
    cfg = Config()
    cfg.set_main_option("script_location", str(PROJECT_ROOT / "alembic"))
    return cfg


def _app_tables(engine):
    inspector = sa_inspect(engine)
    table_names = set(inspector.get_table_names())
    table_names.discard("alembic_version")
    return table_names


def test_migration_file_is_no_longer_a_stub():
    """upgrade()/downgrade() bodies must not be the autogenerated ``pass`` stub."""
    source = MIGRATION_FILE.read_text(encoding="utf-8")
    stub_lines = [ln for ln in source.splitlines() if ln.strip() == "pass"]
    assert not stub_lines, (
        f"migration still contains {len(stub_lines)} bare 'pass' stub line(s)"
    )


def test_upgrade_head_creates_exactly_metadata_tables(alembic_config):
    command.upgrade(alembic_config, "head")

    engine = create_engine(alembic_config.get_main_option("sqlalchemy.url"))
    try:
        created = _app_tables(engine)
    finally:
        engine.dispose()

    assert created == EXPECTED_TABLES, (
        f"missing={EXPECTED_TABLES - created}, unexpected={created - EXPECTED_TABLES}"
    )


def test_downgrade_base_removes_all_app_tables(alembic_config):
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")

    engine = create_engine(alembic_config.get_main_option("sqlalchemy.url"))
    try:
        remaining = _app_tables(engine)
    finally:
        engine.dispose()

    assert remaining == set(), f"downgrade left tables behind: {remaining}"
