"""LLMReport ORM model — stores generated fraud analysis reports."""

import enum
import uuid

from sqlalchemy import ForeignKey, Index, Integer, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from src.models.base import BaseModel


class LLMReportStatus(str, enum.Enum):
    """Report generation status."""

    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"


class LLMReport(BaseModel):
    """Report generated by the LLM worker for a fraudulent transaction."""

    __tablename__ = "llm_reports"

    # uq_llm_reports_transaction_id is created by migration b81e3031f84b and is
    # what makes a redelivered report detectable (the worker treats the
    # IntegrityError as success). It is declared here too so autogenerate cannot
    # emit drop_constraint and silently re-enable duplicate reports.
    __table_args__ = (
        Index("ix_llm_reports_transaction_id", "transaction_id"),
        UniqueConstraint("transaction_id", name="uq_llm_reports_transaction_id"),
    )

    transaction_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("transactions.id", ondelete="CASCADE"),
        nullable=False,
    )
    report_text: Mapped[str] = mapped_column(Text, nullable=True)
    model_name: Mapped[str] = mapped_column(String(100), nullable=False)
    status: Mapped[LLMReportStatus] = mapped_column(
        String(20),
        default=LLMReportStatus.PENDING,
        nullable=False,
    )
    generation_time_ms: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )
    retry_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
