"""LLMReport ORM model — stores generated fraud analysis reports."""

import enum
import uuid

from sqlalchemy import ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from src.models.base import BaseModel


class LLMReportStatus(str, enum.Enum):
    """Report generation status."""

    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"


class LLMReport(BaseModel):
    """Report generated by the LLM worker for a fraudulent transaction."""

    __tablename__ = "llm_reports"

    transaction_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("transactions.id", ondelete="CASCADE"),
        nullable=False,
    )
    report_text: Mapped[str] = mapped_column(Text, nullable=True)
    model_name: Mapped[str] = mapped_column(String(100), nullable=False)
    status: Mapped[LLMReportStatus] = mapped_column(
        String(20),
        default=LLMReportStatus.PENDING,
        nullable=False,
    )
    generation_time_ms: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
    )
    retry_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
